swagger: '2.0'
info:
  version: v0
  title: Data2Action - Flooding Impacts
host: staging.api-flooding.data2action.tech
schemes:
  - https
paths:
  /:
    get:
      description: Swagger Document
      produces:
        - application/yaml
      responses:
        '200':
          description: 200 response
          schema:
            $ref: '#/definitions/Empty'
  /v0/stats:
    get:
      description: Get information about the Flood impacts API
      produces:
        - application/json
      responses:
        '200':
          description: Get information about the Flood impacts API
          schema:
            $ref: '#/definitions/APIStats'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/UnknownError'
  /v0/impacts:
    get:
      description: Get flood impacts for a certain date & time. If no datetime specified, the most recent prediction is delivered.
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ImpactDate'
        - $ref: '#/parameters/ImpactFIPS'
        - $ref: '#/parameters/ImpactScope'
        - $ref: '#/parameters/ImpactStructureType'
      responses:
        '200':
          description: The flood impacts at a DateTime
          schema:
            type: object
            required:
              - request
              - impacts
            properties:
              request:
                $ref: '#/definitions/ImpactsRequest'
              impacts:
                $ref: '#/definitions/FloodImpacts'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/UnknownError'
  /v0/notable-forecasts:
    get:
      description: A list of all available Notable Forecasts.
      produces:
        - application/json
      responses:
        '200':
          description: List of Notable Forecasts
          schema:
            type: array
            items:
              $ref: '#/definitions/NotableForecast'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/UnknownError'
  /v0/notable-forecast/{event}/impacts:
    get:
      description: Get flood impacts for a Notable Forecast at a certain date & time. If no datetime specified, the start date of the forecast is delivered.
      produces:
        - application/json
      parameters:
        - name: event
          in: path
          required: true
          description: The notable forecast ID which can be found at "/v0/notable-forecasts"
          type: string
          x-example: 2024-hurricane-helene
        - $ref: '#/parameters/ImpactDate'
        - $ref: '#/parameters/ImpactFIPS'
        - $ref: '#/parameters/ImpactScope'
        - $ref: '#/parameters/ImpactStructureType'
      responses:
        '200':
          description: The flood impacts at a DateTime during a Notable Forecast
          schema:
            type: object
            required:
              - request
              - impacts
            properties:
              request:
                $ref: '#/definitions/NotableImpactsRequest'
              impacts:
                $ref: '#/definitions/FloodImpacts'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/UnknownError'
parameters:
  ImpactDate:
    name: date
    in: query
    required: false
    description: A 10-character string representing a datetime in the form of YYYYMMDDHH where "YYYY" is a 4-digit year, "MM" is a 2-digit month (01-12), "DD" is a 2-digit day (01-31), and "HH" is a 2-digit hour(00-23).
    x-example: '2025062023'
    type: string
  ImpactFIPS:
    name: fips
    in: query
    required: false
    description: 'The desired granularity of flood impacts. Valid values are: "state", "county", "tract", or "block-group". '
    x-example: county
    default: state
    type: string
    enum:
      - state
      - county
      - tract
      - block-group
  ImpactScope:
    name: scope
    in: query
    required: false
    description: For the returned granularity, you can scope the result set to any FIPS code that starts with this value. For example, specifying "47" would return only values for the state of Tennessee.
    x-example: '47'
    type: string
  ImpactStructureType:
    name: feature-type
    in: query
    required: false
    description: 'Filter the results to a certain type of structure. Accepted values are: "building", "power" (Power Stations) or "ust" (Underground Storage Tanks). Not specifying a value returns all structure types.'
    x-example: power
    type: string
    enum:
      - building
      - power
      - ust
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      type: object
      properties:
        error:
          type: string
          example: Not Found
  UnknownError:
    description: An unknown error occurred
    schema:
      type: object
      properties:
        error:
          type: string
          example: Unknown error occurred
definitions:
  DateTime:
    type: object
    required:
      - year
      - month
      - day
      - hour
    properties:
      year:
        type: string
        description: A 4-digit year
        example: '2025'
      month:
        type: string
        description: A 2-digit month
        example: '06'
        enum:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
      day:
        type: string
        description: A 2-digit day
        example: '20'
        enum:
          - '00'
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
          - '26'
          - '27'
          - '28'
          - '29'
          - '30'
          - '31'
      hour:
        type: string
        description: A 2-digit hour
        example: '23'
        enum:
          - '00'
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
  ScopeOrOmit:
    type: object
    description: Geographic scope of the data
    properties:
      STATE:
        description: State FIPS codes included in the scope
        type: object
        additionalProperties:
          type: object
          properties:
            name:
              type: string
              description: The name of the state
              example: Florida
          required:
            - name
        example:
          '12':
            name: Florida
          '13':
            name: Georgia
      COUNTY:
        description: County FIPS codes included in the scope
        type: object
        additionalProperties:
          type: object
          properties:
            name:
              type: string
              description: The name of the county
              example: Dade County
          required:
            - name
        example:
          '12025':
            name: Dade County
  NotableImpactsRequest:
    allOf:
      - type: object
        required:
          - event
        properties:
          event:
            type: string
            example: 2024-hurricane-helene
      - $ref: '#/definitions/ImpactsRequest'
  FloodImpacts:
    type: object
    description: The number of impacted structures from the requested time looking out 16 hours organized by FIPS code
    additionalProperties:
      type: object
      description: The number of impacted structures predicted at each hour where 't_1' is for the request DateTime and 't_17' is the prediction for 16 hours later.
      additionalProperties:
        type: string
        description: The FIPS code
    example:
      '12020':
        t_1: 886
        t_2: 889
        t_3: 901
        t_4: 896
        t_5: 889
        t_6: 881
        t_7: 932
        t_8: 917
        t_9: 1060
        t_10: 1073
        t_11: 1068
        t_12: 1073
        t_13: 1074
        t_14: 1082
        t_15: 944
        t_16: 949
        t_17: 948
  ImpactsRequest:
    type: object
    required:
      - date
    properties:
      date:
        $ref: '#/definitions/DateTime'
      fips:
        $ref: '#/parameters/ImpactFIPS'
      scope:
        $ref: '#/parameters/ImpactScope'
      feature-type:
        $ref: '#/parameters/ImpactStructureType'
      omit:
        $ref: '#/definitions/ScopeOrOmit'
  APIStats:
    type: object
    required:
      - request
      - statistics
    properties:
      request:
        $ref: '#/definitions/Empty'
      statistics:
        type: object
        properties:
          impacts:
            type: object
            properties:
              dates:
                type: object
                required:
                  - start
                properties:
                  start:
                    $ref: '#/definitions/DateTime'
  NotableForecast:
    type: object
    required:
      - request
      - notable-forecast
    properties:
      request:
        $ref: '#/definitions/Empty'
      notable-forecast:
        type: object
        required:
          - id
          - name
          - description
          - dates
          - scope
        properties:
          id:
            type: string
            description: The identifier for a Notable Forecast event
            example: 2024-hurricane-helene
          name:
            type: string
            description: Name of the notable forecast
            example: Hurricane Hele (2024)
          description:
            type: string
            description: Description of the notable forecast
            example: A description of Hurricane Helene in September of 2024
          dates:
            type: object
            required:
              - start
              - end
            properties:
              start:
                $ref: '#/definitions/DateTime'
              end:
                $ref: '#/definitions/DateTime'
          scope:
            $ref: '#/definitions/ScopeOrOmit'
          endpoints:
            type: array
            description: Available API endpoints
            items:
              type: object
              required:
                - url
                - label
              properties:
                url:
                  type: string
                  description: The endpoint URL path
                  example: notable-forecast/2024-hurricane-helene/impacts
                label:
                  type: string
                  description: Human-readable description of the endpoint
                  example: Get the impacts for a given date & time
  Empty:
    type: object
